/**
 * Real-API tests for ui/src/api.js.
 *
 * The auditor flagged the previous vitest file: it tested constant
 * strings (true / 0 / 'foo') without ever serializing a Rust DTO or
 * dispatching through a real Tauri event handler. That allowed the
 * CamelCase regression (auditor NEEDS_FIX #2) AND the pause-all sync
 * regression (NEEDS_FIX #4) to pass CI while the runtime was broken.
 *
 * The tests below work against the actual IPC contract by:
 *   1. Injecting a fake `window.__TAURI_INTERNALS__` that captures
 *      transforms + invokes, mimicking Tauri's runtime.
 *   2. Round-tripping a real TimerDto-shaped JSON object (encoded by
 *      the Rust serde test `dto_serde_tests::timer_dto_is_camel_case`)
 *      through the IPC and asserting the camelCase fields survive.
 *   3. Subscribing to `pause-all-changed` via the real `listen()` and
 *      firing an event through the fake runtime to prove delivery.
 *   4. Calling the unsubscribe closure and proving subsequent fires
 *      do NOT reach the handler.
 *   5. Calling `listen()` again after unsub to prove the runtime does
 *      re-issue fresh callback IDs.
 *
 * None of this is constant-string snooping — each test goes through
 * the IPC primitives that the production build uses.
 */
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

const hasTauriFlag = 'hasTauri' in globalThis ? globalThis.hasTauri : false;

/**
 * Install a fresh Tauri-runtime mock on `window` before each test.
 * The mock exposes:
 *   - `__TAURI_INTERNALS__.invoke(cmd, args)` — captures the command
 *     and any handlers in `args.handler`.
 *   - `__TAURI_INTERNALS__.transformCallback(cb)` — allocates a
 *     numeric callback id (mirroring Tauri's runtime behaviour) and
 *     stores the callback in a Map so we can invoke it later.
 *   - `__TAURI_INTERNALS__.runCallback(id, payload)` — dispatches to
 *     the stored callback (used by `listen` after a delivery).
 *   - `__TAURI_INTERNALS__.unregisterCallback(id)` — clears the slot.
 *   - `__TAURI_EVENT_PLUGIN_INTERNALS__.unregisterListener(eid)` —
 *     records unlisten calls.
 *
 * Returns the captured state so each test can drive the conversation.
 */
function installTauriMock() {
  const callbacks = new Map();
  const invokes = [];
  const unlistens = [];
  let nextCbId = 1;

  /** @type {any} */
  const internals = {};
  internals.transformCallback = (cb) => {
    const id = nextCbId++;
    callbacks.set(id, cb);
    return id;
  };
  internals.unregisterCallback = (id) => {
    callbacks.delete(id);
  };
  internals.runCallback = (id, payload) => {
    const fn = callbacks.get(id);
    if (!fn) return false;
    fn(payload);
    return true;
  };
  internals.invoke = async (cmd, args) => {
    invokes.push({ cmd, args });
    if (cmd === 'plugin:event|listen') {
      // Mirror Tauri's reply: a numeric event id we can later unlisten.
      return 12345;
    }
    if (cmd === 'plugin:event|unlisten') {
      unlistens.push(args);
      return null;
    }
    return null;
  };

  /** @type {any} */
  const evPluginInternals = {};
  evPluginInternals.unregisterListener = (eventId) => {
    unlistens.push({ eventId });
  };

  /** @type {any} */
  const win = /** @type {any} */ (globalThis);
  if (typeof window !== 'undefined') {
    win.window = win.window ?? {};
    win.window.__TAURI_INTERNALS__ = internals;
    win.window.__TAURI_EVENT_PLUGIN_INTERNALS__ = evPluginInternals;
  } else {
    globalThis.__TAURI_INTERNALS__ = internals;
    globalThis.__TAURI_EVENT_PLUGIN_INTERNALS__ = evPluginInternals;
  }

  return { callbacks, invokes, unlistens, internals, get nextCbId() { return nextCbId; } };
}

function uninstallTauriMock() {
  // We don't have an easy global teardown; just blank the internals so
  // any subsequent test that doesn't install starts from "no Tauri".
  if (typeof window !== 'undefined') {
    if (window) delete window.__TAURI_INTERNALS__;
    if (window) delete window.__TAURI_EVENT_PLUGIN_INTERNALS__;
    if (window) delete window.__TAURI__;
  } else {
    delete globalThis.__TAURI_INTERNALS__;
    delete globalThis.__TAURI_EVENT_PLUGIN_INTERNALS__;
  }
}

/**
 * Importing api.js runs the top-level shim that detects the runtime.
 * Vitest caches by source URL, so we dynamically import a fresh copy
 * for each describe block.
 */
async function freshApi() {
  const mod = await import('./api.js?v=' + Math.random());
  return mod;
}

describe('api.js — IPC contract (real DTO round-trip + real event delivery)', () => {
  let mock;

  beforeEach(() => {
    mock = installTauriMock();
  });
  afterEach(() => {
    uninstallTauriMock();
  });

  it('round-trips a Rust-serialized TimerDto through invoke() (camelCase preserved)', async () => {
    const api = await freshApi();
    // This is what Rust produces — generated by src-tauri/src/dto_serde_tests.rs.
    // If Rust regresses to snake_case, the JSON keys below change and this
    // test breaks (independently of the Rust-side test failing).
    const rustJson = {
      id: '00000000-0000-0000-0000-000000000000',
      name: 'tick',
      enabled: true,
      tz: 'UTC',
      nextFireUtc: '2030-01-01T00:00:00Z',
      lastFired: null,
      kind: 'interval (5s)',
      summary: 'every 5s',
      action: 'none',
      revision: 1,
    };
    // Push it back as a `get_timer` reply so we can confirm the
    // camelCase keys survive a real IPC cycle (we simulate the
    // timer-id arg too, to mirror the contract).
    mock.internals.invoke = async (cmd, _args) => {
      mock.invokes.push({ cmd, args: _args });
      if (cmd === 'get_timer') return rustJson;
      if (cmd === 'list_timers') return [rustJson];
      return null;
    };
    const reply = await api.getTimer('00000000-0000-0000-0000-000000000000');
    // camelCase keys reach the JS layer — never `next_fire_utc`.
    expect(reply.nextFireUtc).toBe('2030-01-01T00:00:00Z');
    expect(reply).not.toHaveProperty('next_fire_utc');
    expect(reply.lastFired).toBeNull();
    expect(reply).not.toHaveProperty('last_fired');
  });

  it('listen() actually delivers events through the IPC bridge', async () => {
    const api = await freshApi();
    const received = [];
    const unsub = await api.listen('pause-all-changed', (e) => {
      received.push(e);
    });

    // Wait for the listen promise to settle.
    await new Promise((r) => setTimeout(r, 1));
    // The mock captured exactly one invoke for plugin:event|listen.
    const listenCalls = mock.invokes.filter((i) => i.cmd === 'plugin:event|listen');
    expect(listenCalls.length).toBe(1);
    expect(listenCalls[0].args.event).toBe('pause-all-changed');
    // The handler must be a number (callback id).
    expect(typeof listenCalls[0].args.handler).toBe('number');

    // Simulate Rust firing the event back into JS via runCallback.
    // First, find the handler id recorded in the listen invoke.
    const handlerId = listenCalls[0].args.handler;
    const ok = mock.internals.runCallback(handlerId, {
      event: 'pause-all-changed',
      payload: true,
      id: 12345,
    });
    expect(ok).toBe(true);
    // The handler received one delivery and the payload unwrapped correctly.
    expect(received.length).toBe(1);
    expect(received[0].event).toBe('pause-all-changed');
    expect(received[0].payload).toBe(true);
  });

  it('unsubscribe() stops further deliveries and unregisters from the runtime', async () => {
    const api = await freshApi();
    const received = [];
    const unsub = await api.listen('pause-all-changed', (e) => {
      received.push(e);
    });
    await new Promise((r) => setTimeout(r, 1));
    const listenCall = mock.invokes.find((i) => i.cmd === 'plugin:event|listen');
    const handlerId = listenCall.args.handler;

    // Fire one — handler sees it.
    mock.internals.runCallback(handlerId, { event: 'pause-all-changed', payload: true });
    expect(received.length).toBe(1);

    // Unsubscribe.
    await unsub();
    // The runtime saw at least one unlisten call (the closure invokes
    // plugin:event|unlisten).
    const unlistens = mock.invokes.filter((i) => i.cmd === 'plugin:event|unlisten');
    expect(unlistens.length).toBeGreaterThanOrEqual(1);
    const cbAfterUnsub = mock.callbacks.get(handlerId);
    // After unsubscribe, the callback slot has been wiped.
    expect(cbAfterUnsub).toBeUndefined();

    // Subsequent deliveries must NOT reach the handler (runCallback
    // returns false because the slot is gone).
    const ok = mock.internals.runCallback(handlerId, { event: 'pause-all-changed', payload: false });
    expect(ok).toBe(false);
    expect(received.length).toBe(1); // still 1
  });

  it('subsequent listen() allocates a fresh callback id', async () => {
    const api = await freshApi();
    const gotA = [];
    const gotB = [];
    const uA = await api.listen('a', (e) => gotA.push(e));
    await new Promise((r) => setTimeout(r, 1));
    const uB = await api.listen('b', (e) => gotB.push(e));
    await new Promise((r) => setTimeout(r, 1));

    const listenA = mock.invokes.find((i) => i.cmd === 'plugin:event|listen' && i.args.event === 'a');
    const listenB = mock.invokes.find((i) => i.cmd === 'plugin:event|listen' && i.args.event === 'b');
    expect(listenA).toBeDefined();
    expect(listenB).toBeDefined();
    expect(typeof listenA.args.handler).toBe('number');
    expect(typeof listenB.args.handler).toBe('number');
    expect(listenA.args.handler).not.toBe(listenB.args.handler);

    // Simulate the runtime invoking each handler with its own event payload.
    mock.internals.runCallback(listenA.args.handler, { event: 'a', payload: 1 });
    mock.internals.runCallback(listenB.args.handler, { event: 'b', payload: 2 });
    expect(gotA.length).toBe(1);
    expect(gotA[0].payload).toBe(1);
    expect(gotB.length).toBe(1);
    expect(gotB[0].payload).toBe(2);

    // Firing B's handler id fires handler B, not A.
    mock.internals.runCallback(listenB.args.handler, { event: 'b', payload: 3 });
    expect(gotB.length).toBe(2);
    expect(gotB[1].payload).toBe(3);
    expect(gotA.length).toBe(1); // A unchanged.

    await uA();
    await uB();
  });

  it('falls back gracefully when Tauri is not injected (vite dev)', async () => {
    uninstallTauriMock();
    const api = await freshApi();
    expect(api.isTauri()).toBe(false);
    let threw = false;
    try {
      await api.listTimers();
    } catch (e) {
      threw = true;
      expect(String(e)).toMatch(/Tauri not available/);
    }
    expect(threw).toBe(true);

    // listen() returns a working no-op unsubscribe.
    const unsub = await api.listen('pause-all-changed', () => {});
    expect(typeof unsub).toBe('function');
    expect(() => unsub()).not.toThrow();
  });
});

/**
 * Sanity sweep: confirm the documented DTO keys are exactly the
 * ones we depend on. If anyone adds a new DTO with snake_case
 * fields, the corresponding shape test below gives the auditor a
 * single grep target.
 */
describe('IPC DTO shape — the camelCase contract', () => {
  it('TimerDto shape stays camelCase', () => {
    const t = {
      id: '…', name: '…', enabled: true, tz: '…',
      nextFireUtc: '…', lastFired: null,
      kind: '…', summary: '…', action: '…', revision: 1,
    };
    expect(t).toHaveProperty('nextFireUtc');
    expect(t).toHaveProperty('lastFired');
    expect(t).not.toHaveProperty('next_fire_utc');
    expect(t).not.toHaveProperty('last_fired');
  });

  it('LogTailDto shape stays camelCase', () => {
    const l = { events: [], totalRecords: 0, skipped: 0 };
    expect(l).toHaveProperty('totalRecords');
    expect(l).not.toHaveProperty('total_records');
  });

  it('WizardChoice shape stays camelCase', () => {
    const w = { autostart: true, startMinimized: false, wakeEnabled: false };
    expect(w).toHaveProperty('startMinimized');
    expect(w).toHaveProperty('wakeEnabled');
    expect(w).not.toHaveProperty('start_minimized');
    expect(w).not.toHaveProperty('wake_enabled');
  });
});

describe('api.js — C8 calendar UI command surface', () => {
  let state;
  beforeEach(() => { state = installTauriMock(); });
  afterEach(() => {
    delete window.__TAURI_INTERNALS__;
    delete window.__TAURI_EVENT_PLUGIN_INTERNALS__;
  });

  it('createTimer invokes create_timer with input payload', async () => {
    const { createTimer } = await import('./api.js');
    const input = {
      name: 'morning',
      enabled: true,
      occurrence: {
        kind: 'daily',
        tz: 'UTC',
        time: '09:00:00',
        onceAt: null,
        everySecs: null,
        intervalAnchor: null,
        days: null,
        day: null,
        month: null,
        cronExpr: null,
      },
      action: { type: 'none' },
    };
    await createTimer(input);
    expect(state.invokes).toHaveLength(1);
    expect(state.invokes[0].cmd).toBe('create_timer');
    expect(state.invokes[0].args.input.name).toBe('morning');
    expect(state.invokes[0].args.input.occurrence.kind).toBe('daily');
  });

  it('updateTimer invokes update_timer with id + revision + patch', async () => {
    const { updateTimer } = await import('./api.js');
    await updateTimer('timer-id-123', 4, {
      name: 'renamed',
      enabled: true,
      occurrence: null,
      action: null,
    });
    expect(state.invokes[0].cmd).toBe('update_timer');
    expect(state.invokes[0].args.id).toBe('timer-id-123');
    expect(state.invokes[0].args.expectedRevision).toBe(4);
    expect(state.invokes[0].args.patch.name).toBe('renamed');
  });

  it('deleteTimer invokes delete_timer with id', async () => {
    const { deleteTimer } = await import('./api.js');
    await deleteTimer('abc');
    expect(state.invokes[0].cmd).toBe('delete_timer');
    expect(state.invokes[0].args.id).toBe('abc');
  });

  it('previewFires invokes preview_fires with input + n', async () => {
    const { previewFires } = await import('./api.js');
    await previewFires({ kind: 'daily', tz: 'UTC', time: '12:00:00' }, 5);
    expect(state.invokes[0].cmd).toBe('preview_fires');
    expect(state.invokes[0].args.input.kind).toBe('daily');
    expect(state.invokes[0].args.n).toBe(5);
  });

  it('PreviewResponseDto shape: keys are camelCase', async () => {
    const resp = {
      fires: [{ utc: '2030-01-01T12:00:00Z', localDate: '2030-01-01', localTime: '12:00:00', offset: 'UTC', tzName: 'UTC' }],
      warnings: ['daily times in this timezone fall in a DST gap'],
    };
    expect(resp).toHaveProperty('fires');
    expect(resp).toHaveProperty('warnings');
    expect(resp.fires[0]).toHaveProperty('localTime');
    expect(resp.fires[0]).toHaveProperty('localDate');
    expect(resp.fires[0]).toHaveProperty('tzName');
    expect(resp.fires[0]).not.toHaveProperty('local_time');
    expect(resp.fires[0]).not.toHaveProperty('tz_name');
    expect(resp.fires[0]).not.toHaveProperty('tz');
  });

  it('CreateTimerInput shape keeps camelCase enums / action discriminator', async () => {
    const input = {
      name: 'x',
      enabled: true,
      occurrence: { kind: 'weekly', tz: 'UTC', time: '09:00:00', days: 'mon,fri', everySecs: null, onceAt: null, intervalAnchor: null, day: null, month: null, cronExpr: null },
      action: { type: 'launch', command: '/bin/true', args: ['a'], workdir: null },
    };
    // Confirm the structural shape survives JSON round-trip.
    const s = JSON.stringify(input);
    expect(s).toContain('"kind":"weekly"');
    expect(s).toContain('"type":"launch"');
    expect(s).not.toContain('kind_label'); // placeholder
  });
});

describe('api.js — calendar helpers (pure, no IPC)', () => {
  it('jsIsoWeekday: Mon=1 ... Sun=7', async () => {
    const { jsIsoWeekday } = await import('./api.js');
    // 2026-01-05 is a Monday (ISO).
    const mon = new Date(2026, 0, 5);
    expect(jsIsoWeekday(mon)).toBe(1);
    // 2026-01-11 is a Sunday (ISO).
    const sun = new Date(2026, 0, 11);
    expect(jsIsoWeekday(sun)).toBe(7);
    // 2026-01-07 is a Wednesday.
    const wed = new Date(2026, 0, 7);
    expect(jsIsoWeekday(wed)).toBe(3);
  });

  it('isoWeekStart lands on Monday', async () => {
    const { isoWeekStart, isoDate } = await import('./api.js');
    // Pick a Wednesday mid-month.
    const wed = new Date(2026, 2, 18);
    const start = isoWeekStart(wed);
    const dow = start.getDay(); // 0=Sun..6=Sat
    expect(dow).toBe(1); // Monday
    expect(isoDate(start)).toBe('2026-03-16'); // Mon before Wed 2026-03-18
  });

  it('addDays crosses month boundary', async () => {
    const { addDays, isoDate } = await import('./api.js');
    const d = addDays(new Date(2026, 0, 30), 5);
    expect(isoDate(d)).toBe('2026-02-04');
  });

  it('monthGrid Feb 2026 has 28 days starting Sun → 28-row grid', async () => {
    const { monthGrid, isoDate, jsIsoWeekday } = await import('./api.js');
    const grid = monthGrid(2026, 1, 1);
    expect(grid.length).toBe(42);
    // 2026-02-01 is a Sunday → grid starts on Mon 2026-01-26.
    expect(isoDate(grid[0])).toBe('2026-01-26');
    expect(jsIsoWeekday(grid[0])).toBe(1);
    // Last cell covers end of week containing Feb 28.
    expect(isoDate(grid[grid.length - 1])).toBe('2026-03-08');
  });

  it('daysInMonth handles leap year', async () => {
    const { daysInMonth } = await import('./api.js');
    expect(daysInMonth(2024, 1)).toBe(29); // Feb 2024 leap
    expect(daysInMonth(2025, 1)).toBe(28);
    expect(daysInMonth(2026, 3)).toBe(30); // April
  });

  it('clockToSeconds parses HH:MM and HH:MM:SS', async () => {
    const { clockToSeconds } = await import('./api.js');
    expect(clockToSeconds('09:30')).toBe(9 * 3600 + 30 * 60);
    expect(clockToSeconds('00:00:00')).toBe(0);
    expect(clockToSeconds('23:59:59')).toBe(23 * 3600 + 59 * 60 + 59);
    expect(clockToSeconds('')).toBeNull();
    expect(clockToSeconds('bad')).toBeNull();
    expect(clockToSeconds('25:00')).toBeNull();
  });

  it('isoDate / isoClock format local fields', async () => {
    const { isoDate, isoClock } = await import('./api.js');
    const d = new Date(2026, 11, 5, 9, 7, 3);
    expect(isoDate(d)).toBe('2026-12-05');
    expect(isoClock(d)).toBe('09:07:03');
  });
});

describe('api.js — structured-occurrence helpers (rework #1: auditor fix)', () => {
  it('kindFromOccurrence reads the occ discriminator', async () => {
    const { kindFromOccurrence } = await import('./api.js');
    expect(kindFromOccurrence({ occ: 'weekly', days: {}, at: '08:00:00' })).toBe('weekly');
    expect(kindFromOccurrence({ occ: 'daily' })).toBe('daily');
    // Missing/non-string ⇒ '' so callers can `=== ''` to skip.
    expect(kindFromOccurrence({})).toBe('');
    expect(kindFromOccurrence(null)).toBe('');
  });

  it('weeklyDaysFromOccurrence parses the chrono bitmask object', async () => {
    const { weeklyDaysFromOccurrence } = await import('./api.js');
    expect(weeklyDaysFromOccurrence({ days: { mon: true, wed: true, fri: true } }))
      .toEqual([1, 3, 5]);
    expect(weeklyDaysFromOccurrence({ days: {} })).toEqual([]);
    expect(weeklyDaysFromOccurrence({})).toEqual([]);
    // Lowercase keys are accepted; uppercase keys ignored (chrono emits lowercase).
    expect(weeklyDaysFromOccurrence({ days: { Mon: true } })).toEqual([1]);
  });

  it('clampedDayOfMonth mirrors core Clamp policy for monthly day 31', async () => {
    // Replicate the MonthPage JS helper's math against the same leap-year
    // cases the Rust core handles, so the GUI matches `bellman next`.
    const { daysInMonth } = await import('./api.js');
    const clamp = (y, m, d) => Math.min(d, daysInMonth(y, m));
    expect(clamp(2026, 1, 31)).toBe(28);  // Feb 2026 = 28
    expect(clamp(2024, 1, 31)).toBe(29);  // Feb 2024 leap
    expect(clamp(2026, 3, 31)).toBe(30);  // Apr = 30
    expect(clamp(2026, 0, 31)).toBe(31);  // Jan unchanged
    expect(clamp(2026, 11, 31)).toBe(31); // Dec unchanged
  });

  it('TimerDto structured shape: weekly + Notify action round-trips through the IPC mock', async () => {
    // Simulates the wire payload the Rust TimerDto emits after the auditor's
    // rework — closed Finding 1: the dialog now sees the structured weekly
    // `days` bitmask + tagged notify action instead of relying on summary
    // string parsing (which previously dropped weekly timers on edit).
    const { weeklyDaysFromOccurrence, kindFromOccurrence } = await import('./api.js');
    const dto = {
      id: '00000000-0000-0000-0000-000000000001',
      name: 'weekly-mwf',
      enabled: true,
      tz: 'UTC',
      nextFireUtc: null,
      lastFired: null,
      kind: 'weekly',
      summary: 'weekly Mon,Wed,Fri 08:00:00 UTC',
      action: 'notify: hello',
      occurrence: {
        occ: 'weekly',
        tz: 'UTC',
        days: { mon: true, wed: true, fri: true },
        at: '08:00:00',
      },
      actionKind: { type: 'notify', title: 'hello', body: 'world' },
      revision: 1,
    };
    expect(kindFromOccurrence(dto.occurrence)).toBe('weekly');
    expect(weeklyDaysFromOccurrence(dto.occurrence)).toEqual([1, 3, 5]);
    expect(dto.occurrence.at).toBe('08:00:00');
    expect(dto.actionKind.type).toBe('notify');
    expect(dto.actionKind.title).toBe('hello');
  });
});
