[package]
name = "bellman-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Bellman command-line interface"
default-run = "bellman"

[[bin]]
name = "bellman"
path = "src/main.rs"

[dependencies]
bellman-core = { workspace = true }
chrono = { workspace = true, features = ["clock"] }
chrono-tz = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
